### ISSUE TITLE
Readme Remarks

### ISSUE THREAD

**Issue by dargmuesli** [fujaba/fulib#31]
- the Gradle link points to "fulibYaml", not "fulib"
- the "compile" keyword is used, but "implementation" or even "testImplementation" would be better, wouldn't it?
- there's a lost semicolon in the first code example under "Usage"

**Comment by Clashsoft** [comment]
Thanks for reporting. The first and last points are fixed in 0df6e7325159c9f6303e90b02dc49d30af79b899. I agree with the second point, however as of the upcoming fulib v1.2 neither compile nor implementation will be used. Instead there will be a new configuration added by the fulibGradle plugin and fulib will become a build-only dependency. So no point in changing now.

**Comment by Clashsoft** [comment]
If you want to check it out, the new usage instructions are now available in the [`develop`](https://github.com/fujaba/fulib/tree/develop) branch.
